---
# file: group_vars 
repo_matrix_ac: https://github.com/matrix-ac/matrix-site.git
repo_registration: https://github.com/matrix-ac/GreatScottHosting.git

cgit_hostname: git.matrix.ac 
cgit_repo_locations: /srv/gitrepos

matrix_hostname: matrix.ac