---
# file: roles/searx/tasks
- name: Install sytem dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - build-essential
    - libxslt-dev
    - python-dev
    - python-virtualenv
    - python-pybabel
    - python-lxml    # Added because low memory
    - python-openssl # Added because low memory
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - uwsgi 
    - uwsgi-plugin-python

- name: Clone Repo
  git: 
    repo: https://github.com/asciimoo/searx.git
    dest: /usr/local/searx
    update: no
    version: v0.10.0

- name: Create a new user
  user:
    name: searx
    system: yes 
    createhome: no
    home: /usr/local/searx

- name: Correct Permissions
  file: 
    path: /usr/local/searx
    owner: searx
    group: searx
    recurse: yes

- block:

  - lineinfile: dest=/usr/local/searx/requirements.txt state=absent regexp='^lxml'
  - lineinfile: dest=/usr/local/searx/requirements.txt state=absent regexp='^pyopenssl'
  
  - name: Install virtual enviromnet dependencies
    pip:
      virtualenv: searx-ve
      virtualenv_site_packages: yes
      virtualenv_python: python2.7
      requirements: requirements.txt
      extra_args: '--no-cache-dir'
      chdir: /usr/local/searx

  - name: Configure secrect key
    replace:
      dest: /usr/local/searx/searx/settings.yml
      regexp: ultrasecretkey
      replace: '{{ searx_secret }}'
      backup: yes

  become: yes
  become_user: searx

- name: SystemD Service
  template: src=searx.service dest=/etc/systemd/system/searx.service

- name: Enabeling and starting searx
  service:
    name: searx
    state: started
    enabled: yes

- name: Add uwsgi config
  template: src=searx.ini.j2 dest=/etc/uwsgi/apps-available/searx.ini

- name: Enable searx with uwsgi
  file: src=/etc/uwsgi/apps-available/searx.ini dest=/etc/uwsgi/apps-enabled/searx.ini owner=root group=root state=link
  notify: restart uwsgi

- name: Add nginx config
  template: src=searx.conf.j2 dest=/etc/nginx/sites-available/searx.conf

- name: Enable searx with nginx
  file: src=/etc/nginx/sites-available/searx.conf dest=/etc/nginx/sites-enabled/searx.conf owner=root group=root state=link
  notify: restart nginx