---
# file: roles/web/tasks
- name: Copy the code from repository
  git: repo={{ repo_matrix_ac }} dest=/root/matrix-site/

- name: Build site
  shell: /usr/bin/jekyll build -s /root/matrix-site/ -d /var/www/html/

